config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'todos#index'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :message, presence: true, length: {minimum:10}
  validates :done, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo  = Todo.new
  end

  def create
    puts "ici"
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def todo_params
    params.require(:todo).permit(:message,:done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo do |form| %>
<div>
    <%= form.label :message %><br>
    <%= form.text_field :message %>
    <%= @todo.errors.full_messages_for(:message).each do |m| %>
        <div> <%= m %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :done %><br>
    <%= form.check_box :done %>
    <%= @todo.errors.full_messages_for(:done).each do |m| %>
        <div> <%= m %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/index.html.erb
<h1> Todo list items : </h1>
<ul>
  <%@todos.each do |item|%>
    <li>

        <a href="<%= todo_path(item.id) %>">  <%= item.message %>  </a>
    </li>
  <% end %>
</ul>

app/views/todos/new.html.erb
<h1>New todo</h1>


<%= render "form", todo: @todo %>

app/views/todos/show.html.erb
<h1><%= @todo.message %></h1>

<p><%= @todo.done %></p>

<ul>
  <li><%= link_to "Edit", edit_todo_path(@todo) %></li>
  <li><%= link_to "Destroy", todo_path(@todo), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure ?"
  }%>
</ul>